export type PermissionToggleVisibility = {
    anonymousChat?: boolean;
    groupChat?: boolean;
    /** Advice-seeker account: free display-name entry (ORISO-Admin#602). */
    displayNameEditable?: boolean;
    /** Advice-seeker account: may leave an e-mail address (ORISO-Admin#602). */
    askerEmail?: boolean;
    calls?: boolean;
    supervision?: boolean;
    supervisionAnonymousChats?: boolean;
    supervisionOneOnOneChats?: boolean;
    audioCalls?: boolean;
    audioCallsAnonymousChats?: boolean;
    audioCallsOneOnOneChats?: boolean;
    audioCallsGroupChats?: boolean;
    audioCallsSupervisionChats?: boolean;
    videoCalls?: boolean;
    videoCallsAnonymousChats?: boolean;
    videoCallsOneOnOneChats?: boolean;
    videoCallsGroupChats?: boolean;
    videoCallsSupervisionChats?: boolean;
    threads?: boolean;
    threadsAnonymousChats?: boolean;
    threadsOneOnOneChats?: boolean;
    threadsGroupChats?: boolean;
    threadsSupervisionChats?: boolean;
    voiceMessages?: boolean;
    voiceMessagesAnonymousChats?: boolean;
    voiceMessagesOneOnOneChats?: boolean;
    voiceMessagesGroupChats?: boolean;
    voiceMessagesSupervisionChats?: boolean;
    mediaUpload?: boolean;
    mediaUploadAnonymousChats?: boolean;
    mediaUploadOneOnOneChats?: boolean;
    mediaUploadGroupChats?: boolean;
    mediaUploadSupervisionChats?: boolean;
    mediaInlineDisplay?: boolean;
    mediaInlineDisplayAnonymousChats?: boolean;
    mediaInlineDisplayOneOnOneChats?: boolean;
    mediaInlineDisplayGroupChats?: boolean;
    mediaInlineDisplaySupervisionChats?: boolean;
    mediaAiScan?: boolean;
    mediaAiScanAnonymousChats?: boolean;
    mediaAiScanOneOnOneChats?: boolean;
    mediaAiScanGroupChats?: boolean;
    mediaAiScanSupervisionChats?: boolean;
};
