export const resources = {
    de: {
        proposal: {
            preview: 'Designvorschlag · Beispieldaten, keine Konto- oder Themenänderung',
            title: 'Themen Ihrer Beratung',
            name: 'Anzeigename',
            choose: 'Themen auswählen',
            description: 'Suchen Sie ein Thema und überprüfen Sie Ihre Auswahl, bevor Sie sie übernehmen.',
            search: 'Themen suchen',
            selected: 'Ausgewählt ({{count}})',
            apply: 'Anwenden',
            cancel: 'Abbrechen',
            remove: '{{name}} entfernen',
            locked: 'Fest vorgegeben',
            lockedHint: 'Fest vorgegebene Themen bleiben ausgewählt.',
            minimum: 'Wählen Sie mindestens ein Thema.',
            single: 'Sie können genau ein Thema Ihrer Beratungsstelle wählen.',
            agencyOnly: 'Zur Auswahl stehen die freigegebenen Themen Ihrer Beratungsstelle.',
            catalogue:
                'Zur Auswahl stehen die freigegebenen Themen des Katalogs. Es werden keine neuen Themen erstellt.',
            fixed: 'Dieses Thema wurde in Ihrer Einladung festgelegt.',
            fixtureIcons:
                'Icons aus dem bestehenden ORISO-Katalog. Die Zuordnung zu Beispiel-IDs ist nur für diesen Vorschlag.',
            noIcon: 'Kein Icon hinterlegt',
            noResults: 'Keine passenden Themen gefunden.',
            clear: 'Suche zurücksetzen',
            loading: 'Themen werden geladen …',
            error: 'Die Themen konnten nicht geladen werden.',
            retry: 'Erneut versuchen',
            empty: 'Es stehen keine freigegebenen Themen zur Auswahl. Bitte wenden Sie sich an die einladende Person.',
            summary: 'Übernommene Themen',
            language: 'Sprache',
            count: '{{count}} Themen verfügbar',
        },
    },
    en: {
        proposal: {
            preview: 'Design preview · Example data, no account or topic changes',
            title: 'Your counselling topics',
            name: 'Display name',
            choose: 'Choose topics',
            description: 'Search for a topic and review your selection before applying it.',
            search: 'Search topics',
            selected: 'Selected ({{count}})',
            apply: 'Apply',
            cancel: 'Cancel',
            remove: 'Remove {{name}}',
            locked: 'Required',
            lockedHint: 'Required topics remain selected.',
            minimum: 'Choose at least one topic.',
            single: 'You can choose exactly one topic of your counselling centre.',
            agencyOnly: 'Only the permitted topics of your counselling centre are available.',
            catalogue: 'Choose from the permitted catalogue topics. No new topics are created.',
            fixed: 'This topic was specified in your invitation.',
            fixtureIcons:
                'Icons from the existing ORISO catalogue. Their example-ID mapping is only for this proposal.',
            noIcon: 'No icon supplied',
            noResults: 'No matching topics found.',
            clear: 'Clear search',
            loading: 'Loading topics …',
            error: 'The topics could not be loaded.',
            retry: 'Try again',
            empty: 'No permitted topics are available. Please contact the person who invited you.',
            summary: 'Applied topics',
            language: 'Language',
            count: '{{count}} topics available',
        },
    },
};
